variables:
- name: DefaultBuildConfiguration
  value: Debug
- name: DefaultBuildPlatform
  value: 'any cpu'
- name: ApkName
  value: AndroidControlGallery.AndroidControlGallery.apk
- name: IpaName
  value: XamarinFormsControlGalleryiOS.ipa
- name: SolutionFile
  value: Xamarin.Forms.sln
- name: BuildVersion
  value: $[counter(variables['build.sourcebranch'], 1)]
- name: BuildVersion42
  value: $[counter('xf-nuget-counter', 991212)]
- name: BuildVersion43
  value: $[counter('xf-nuget-counter', 991212)]
- name: BuildVersion44
  value: $[counter('xf-nuget-counter', 991212)]
- name: patch
  value: $[counter(variables['build.reason'], 992000)]
- name: NUGET_VERSION
  value: 5.0.2
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: true
- name: DOTNET_VERSION
  value: 3.0.100
- name: winVmImage
  value: XamarinForms

trigger:
  branches:
    include:
    - master
    - 3.*
    - 4.*
  tags:
    include:
    - '*'
  paths:
    exclude:
    - README.md

pr:
  autoCancel: false
  branches:
    include:
    - master
    - 4.*
    - 3.*

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master 

resources:
  repositories:
    - repository: xamarin-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin

stages:
  - stage: Windows
    displayName: Build Binaries
    jobs:
      - template: build/steps/build-windows.yml
        parameters:
          name: win
          displayName: Build Windows Phase
          vmImage: $(winVmImage)
          msbuildExtraArguments: '/nowarn:"APPX0107;APPX0102;APPX4001;CS0109;MSB3245;MSB3073;MSB3276;MSB3277;VSX1000;XA0113;XA4216;XA4216APPX0107;VSX1000" /p:CreateAllAndroidTargets=true /bl:$(Build.ArtifactStagingDirectory)\win.binlog'
          buildConfiguration: $(DefaultBuildConfiguration)
          buildPlatform: $(DefaultBuildPlatform)